/**
 * Reads raw per-sample latencies from scripts/results/*.json and produces:
 *   - a stats bundle (scripts/results/latency-stats.json)
 *   - LaTeX-ready tables (scripts/results/latency-stats.tex) covering
 *     descriptives, the bootstrap 95 % CI on the mean, and a one-sample
 *     t-test against the 15 s design target.
 *
 * Companion to the LaTeX in chapter 5 §5.4 — Chapter 5 imports the .tex
 * table with \input{}, so re-running this script is how the thesis
 * numbers refresh.
 *
 *   cd GOP-MVP
 *   npx tsx scripts/analyze-latency.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { summary, bootstrapMeanCI, oneSampleTTest } from '../src/lib/stats/descriptive'

const RESULTS_DIR = join(process.cwd(), 'scripts', 'results')

// Design target from the requirements, in the same unit the measurements
// are captured in (milliseconds).
const TARGET_MS = 15_000

interface Bundle {
  label: string
  file: string
  samples: number[]
}

function loadSamples(): Bundle[] {
  const out: Bundle[] = []

  const orch = join(RESULTS_DIR, 'orchestrator-quality.json')
  if (existsSync(orch)) {
    const j = JSON.parse(readFileSync(orch, 'utf8'))
    const samples = j?.latency?.samples ?? j?.latency?.durations
    if (Array.isArray(samples) && samples.length) {
      out.push({ label: 'Full graph assembly', file: 'orchestrator-quality.json', samples })
    } else {
      console.warn(`[analyze] ${orch} has aggregate but no samples — re-run the measurement to persist raw values`)
    }
  }

  const mapping = join(RESULTS_DIR, 'mapping-quality.json')
  if (existsSync(mapping)) {
    const j = JSON.parse(readFileSync(mapping, 'utf8'))
    const samples = j?.latency?.samples ?? j?.latency?.durations
    if (Array.isArray(samples) && samples.length) {
      out.push({ label: 'Patient synchronization', file: 'mapping-quality.json', samples })
    } else {
      console.warn(`[analyze] ${mapping} has aggregate but no samples — re-run the measurement to persist raw values`)
    }
  }

  return out
}

function fmt(n: number, digits = 1): string {
  if (!Number.isFinite(n)) return '—'
  return n.toFixed(digits)
}

function fmtP(p: number): string {
  if (!Number.isFinite(p)) return '—'
  if (p < 1e-6) return '< 10^{-6}'
  return p.toExponential(2)
}

function main() {
  const bundles = loadSamples()
  if (bundles.length === 0) {
    console.error('[analyze] No sample data found. Run measure-mapping-quality.ts and measure-orchestrator-quality.ts first.')
    process.exit(1)
  }

  const perLabel: Record<string, any> = {}
  const rows: string[] = []
  const bootstrapRows: string[] = []
  const tRows: string[] = []

  for (const b of bundles) {
    const s = summary(b.samples)
    const ci = bootstrapMeanCI(b.samples, { iterations: 10_000, seed: 42 })
    const t = oneSampleTTest(b.samples, TARGET_MS)

    perLabel[b.label] = {
      n: s.n,
      mean: s.mean, sd: s.sd, median: s.median, q1: s.q1, q3: s.q3, iqr: s.iqr,
      min: s.min, max: s.max,
      bootstrap95: { lo: ci.ciLo, hi: ci.ciHi, iterations: ci.iterations, seed: ci.seed },
      tTest: { target: t.target, t: t.t, df: t.df, pTwoSided: t.pTwoSided, meanDiff: t.meanDiff, cohensD: t.cohensD },
      samples: b.samples,
    }

    console.log(`\n${b.label}  (n=${s.n})`)
    console.log(`  mean = ${fmt(s.mean)} ms   sd = ${fmt(s.sd, 2)} ms   median = ${fmt(s.median)}   IQR = ${fmt(s.iqr)}`)
    console.log(`  bootstrap 95 % CI on the mean: [${fmt(ci.ciLo)}, ${fmt(ci.ciHi)}]`)
    console.log(`  one-sample t vs ${TARGET_MS} ms target: t(${t.df}) = ${fmt(t.t, 2)}, p ${fmtP(t.pTwoSided)}, d = ${fmt(t.cohensD, 2)}`)

    // Descriptive stats row for the shared LaTeX table.
    rows.push(
      `${b.label} & ${s.n} & ${fmt(s.mean)} & ${fmt(s.sd, 2)} & ${fmt(s.median)} & ${fmt(s.iqr)} & ${fmt(s.min)} & ${fmt(s.max)} \\\\`,
    )
    // Bootstrap CI row.
    bootstrapRows.push(
      `${b.label} & ${fmt(s.mean)} & ${fmt(ci.ciLo)} & ${fmt(ci.ciHi)} & ${ci.iterations} \\\\`,
    )
    // One-sample t-test row.
    tRows.push(
      `${b.label} & ${fmt(t.t, 2)} & ${t.df} & ${fmtP(t.pTwoSided)} & ${fmt(t.cohensD, 2)} \\\\`,
    )
  }

  const tex = [
    `% Auto-generated by scripts/analyze-latency.ts — do not edit by hand.`,
    `% Re-run: cd GOP-MVP && npx tsx scripts/analyze-latency.ts`,
    ``,
    `\\begin{table}[htbp]`,
    `\\centering`,
    `\\caption{Latency descriptives (ms). Sample standard deviation uses the Bessel-corrected $n-1$ denominator; quartiles are computed with the type-7 rule.}`,
    `\\label{tab:latency-descriptives}`,
    `\\begin{tabular}{lrrrrrrr}`,
    `\\hline`,
    `\\textbf{Path} & \\textbf{n} & \\textbf{Mean} & \\textbf{SD} & \\textbf{Median} & \\textbf{IQR} & \\textbf{Min} & \\textbf{Max} \\\\`,
    `\\hline`,
    ...rows,
    `\\hline`,
    `\\end{tabular}`,
    `\\end{table}`,
    ``,
    `\\begin{table}[htbp]`,
    `\\centering`,
    `\\caption{Bootstrap 95\\,\\% confidence interval on the mean latency (ms). Percentile method, seed 42.}`,
    `\\label{tab:latency-bootstrap}`,
    `\\begin{tabular}{lrrrr}`,
    `\\hline`,
    `\\textbf{Path} & \\textbf{Mean} & \\textbf{CI low} & \\textbf{CI high} & \\textbf{Iterations} \\\\`,
    `\\hline`,
    ...bootstrapRows,
    `\\hline`,
    `\\end{tabular}`,
    `\\end{table}`,
    ``,
    `\\begin{table}[htbp]`,
    `\\centering`,
    `\\caption{Two-sided one-sample $t$-test of the observed latency against the ${TARGET_MS}\\,ms design target. Cohen's $d = (\\bar{x} - \\mu_0) / s$.}`,
    `\\label{tab:latency-ttest}`,
    `\\begin{tabular}{lrrrr}`,
    `\\hline`,
    `\\textbf{Path} & \\textbf{$t$} & \\textbf{df} & \\textbf{$p$} & \\textbf{Cohen's $d$} \\\\`,
    `\\hline`,
    ...tRows,
    `\\hline`,
    `\\end{tabular}`,
    `\\end{table}`,
    ``,
  ].join('\n')

  writeFileSync(join(RESULTS_DIR, 'latency-stats.json'), JSON.stringify({ generatedAt: new Date().toISOString(), targetMs: TARGET_MS, results: perLabel }, null, 2))
  writeFileSync(join(RESULTS_DIR, 'latency-stats.tex'), tex)
  console.log(`\nWrote scripts/results/latency-stats.json and .tex`)
}

main()
