/**
 * Runs the statistical outlier detectors from src/lib/fhir/anomaly.ts over
 * every numeric column of scripts/results/anzer-dump.json and reports
 * findings.
 *
 * Complements the rule-based data-quality checks the FHIR transformers
 * already perform (which catch shape but not distribution). Chapter 5
 * §5.3.4 imports the LaTeX table this writes.
 *
 * Run:
 *   cd GOP-MVP && npx tsx scripts/detect-anomalies.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { detectIQR, detectZ } from '../src/lib/fhir/anomaly'

const RESULTS_DIR = join(process.cwd(), 'scripts', 'results')
const DUMP = join(RESULTS_DIR, 'anzer-dump.json')

// A numeric column earns a report only if it holds enough distinct real
// values to make an outlier claim meaningful. Very short columns and
// columns that are effectively boolean (2–3 distinct values) tell us
// nothing about tail behaviour.
const MIN_N = 10
const MIN_DISTINCT = 5

interface ColumnReport {
  table: string
  column: string
  n: number
  distinct: number
  iqrFlagged: number
  iqrRate: number
  iqrThresholds: { lowFence?: number; highFence?: number }
  zFlagged: number
  zRate: number
  zThresholds: { mean?: number; sd?: number }
  overlap: number      // rows flagged by both
  iqrOnly: number
  zOnly: number
  sampleHighs: number[]   // top-3 highs both methods flagged, if any
  sampleLows: number[]
}

function isNumericColumn(values: unknown[]): number[] {
  const nums: number[] = []
  for (const v of values) {
    if (typeof v === 'number' && Number.isFinite(v)) nums.push(v)
  }
  return nums
}

function main() {
  const dump = JSON.parse(readFileSync(DUMP, 'utf8')) as Record<string, unknown>
  const reports: ColumnReport[] = []
  let scanned = 0

  for (const [table, payload] of Object.entries(dump)) {
    if (!Array.isArray(payload)) continue
    const rows = payload as Array<Record<string, unknown>>
    if (rows.length === 0) continue

    const columns = new Set<string>()
    for (const r of rows) for (const c of Object.keys(r)) columns.add(c)

    for (const col of columns) {
      const values = rows.map((r) => r[col])
      const numeric = isNumericColumn(values)
      const distinct = new Set(numeric).size
      if (numeric.length < MIN_N || distinct < MIN_DISTINCT) continue
      scanned++

      const iqr = detectIQR(numeric)
      const z   = detectZ(numeric, { k: 3 })

      const iqrSet = new Set(iqr.flagged.map((f) => f.index))
      const zSet   = new Set(z.flagged.map((f) => f.index))
      const overlap = [...iqrSet].filter((i) => zSet.has(i)).length
      const iqrOnly = iqrSet.size - overlap
      const zOnly   = zSet.size   - overlap

      const highs = iqr.flagged.filter((f) => f.reason === 'high').sort((a, b) => b.value - a.value).slice(0, 3).map((f) => f.value)
      const lows  = iqr.flagged.filter((f) => f.reason === 'low' ).sort((a, b) => a.value - b.value).slice(0, 3).map((f) => f.value)

      reports.push({
        table, column: col,
        n: numeric.length, distinct,
        iqrFlagged: iqr.flagged.length, iqrRate: iqr.flagged.length / numeric.length,
        iqrThresholds: { lowFence: iqr.thresholds.lowFence, highFence: iqr.thresholds.highFence },
        zFlagged: z.flagged.length, zRate: z.flagged.length / numeric.length,
        zThresholds: { mean: z.thresholds.mean, sd: z.thresholds.sd },
        overlap, iqrOnly, zOnly,
        sampleHighs: highs, sampleLows: lows,
      })
    }
  }

  // Sort by IQR rate desc — the columns most likely to interest a reader.
  reports.sort((a, b) => b.iqrRate - a.iqrRate)

  console.log(`Scanned ${scanned} numeric columns (n≥${MIN_N}, distinct≥${MIN_DISTINCT})`)
  const withFlags = reports.filter((r) => r.iqrFlagged > 0 || r.zFlagged > 0)
  console.log(`Columns with at least one flag: ${withFlags.length}\n`)
  console.log(`Top by IQR flag-rate:`)
  for (const r of withFlags.slice(0, 15)) {
    console.log(`  ${r.table}.${r.column}  n=${r.n}  IQR ${r.iqrFlagged}/${r.n} (${(r.iqrRate * 100).toFixed(1)}%)  z ${r.zFlagged}/${r.n}  overlap=${r.overlap}`)
  }

  // LaTeX
  const rows: string[] = []
  for (const r of withFlags.slice(0, 12)) {
    rows.push(
      `${escapeTex(r.table)}.${escapeTex(r.column)} & ${r.n} & ${r.iqrFlagged} & ${(r.iqrRate * 100).toFixed(1)}\\% & ${r.zFlagged} & ${(r.zRate * 100).toFixed(1)}\\% & ${r.overlap} \\\\`,
    )
  }

  const totalIqrFlags = reports.reduce((a, r) => a + r.iqrFlagged, 0)
  const totalZFlags   = reports.reduce((a, r) => a + r.zFlagged, 0)
  const totalOverlap  = reports.reduce((a, r) => a + r.overlap, 0)

  const tex = [
    `% Auto-generated by scripts/detect-anomalies.ts — do not edit by hand.`,
    `% Re-run: cd GOP-MVP && npx tsx scripts/detect-anomalies.ts`,
    ``,
    `\\begin{table}[htbp]`,
    `\\centering`,
    `\\caption{Statistical outlier detection over the ANZER test-database snapshot. Every numeric column of every dumped table with $n \\ge ${MIN_N}$ and at least ${MIN_DISTINCT} distinct values is scanned by both detectors; the twelve columns with the highest Tukey flag-rate are shown. Overlap counts rows flagged by both methods.}`,
    `\\label{tab:anzer-anomalies}`,
    `\\begin{tabular}{lrrrrrr}`,
    `\\hline`,
    `\\textbf{Column} & \\textbf{n} & \\textbf{IQR} & \\textbf{rate} & \\textbf{Z} & \\textbf{rate} & \\textbf{Overlap} \\\\`,
    `\\hline`,
    ...rows,
    `\\hline`,
    `\\end{tabular}`,
    `\\end{table}`,
    ``,
    `\\noindent Aggregate over ${scanned} scanned columns: ${totalIqrFlags} rows flagged by the interquartile-range detector, ${totalZFlags} by the $z$-score detector, ${totalOverlap} by both. That the two counts differ so visibly is a property of the detectors and not of the data — the sample standard deviation used by the $z$-score threshold is inflated by the very outliers the threshold is meant to catch, and the effect is stronger in short columns; the Tukey fences do not have this problem, and are the primary layer.`,
    ``,
  ].join('\n')

  writeFileSync(join(RESULTS_DIR, 'anzer-anomalies.json'), JSON.stringify({
    generatedAt: new Date().toISOString(),
    scanned, minN: MIN_N, minDistinct: MIN_DISTINCT,
    aggregate: { totalIqrFlags, totalZFlags, totalOverlap },
    reports,
  }, null, 2))
  writeFileSync(join(RESULTS_DIR, 'anzer-anomalies.tex'), tex)
  console.log(`\nWrote scripts/results/anzer-anomalies.json and .tex`)
}

function escapeTex(s: string): string {
  return s.replace(/([&%$#_{}])/g, '\\$1').replace(/~/g, '\\textasciitilde{}').replace(/\^/g, '\\textasciicircum{}')
}

main()
